# excerpt_separator: "<!--more-->"
url: http://cmbybelin.com
name: Capture the Moment by Belin
defaults:
  - scope:
       path: ""
       type: "posts"
    values:
       layout: "blog"
  - scope:
       path: ""
       type: "portfolio"
    values:
       layout: "portfolio"

collections:
  portfolio:
    output: true
