# excerpt_separator: "<!--more-->"
url: http://belindaterrisse.com
name: Belinda Terrisse Portrait photography
defaults:
  - scope:
       path: ""
       type: "posts"
    values:
       layout: "blog"
  - scope:
       path: ""
       type: "portfolio"
    values:
       layout: "portfolio"

collections:
  portfolio:
    output: true
