# excerpt_separator: "<!--more-->"
url: http://belindaterrisse.com
title: Belinda Terrisse portrait photography
description: Photography. The art to capture the right moment, to transfer a feeling and intrigue people.
logo: style/images/sig.png
social:
  type: organization
  links: [ "https://www.facebook.com/belinda.terrisse", "https://www.instagram.com/belindaterrisse", "https://www.pinterest.com/belindaterrisse" ]

email_post_url: https://getsimpleform.com/messages?form_api_token=f4f995dca59e3f566b7d974bf51b46f4

gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

defaults:
  - scope:
       path: ""
       type: "posts"
    values:
       layout: "blog"
  - scope:
       path: ""
       type: "portfolio"
    values:
       layout: "portfolio-category"

collections:
  portfolio:
    output: true
